[package]
name = "rusty-boi"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rb_core = { path = "./rb_core" }
sdl2 = "^0.35.2"